language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.1.0-DEV
  - SYMFONY_VERSION=origin/master

before_script: wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: php mageekguy.atoum.phar

branches:
  except:
    - develop
  only:
    - master

notifications:
  email:
    recipients:
      - ceednee@gmail.com
    on_success: change
    on_failure: always
